### ISSUE TITLE
Download gone?

### ISSUE THREAD

**Issue by mishakim** [HudsonGraeme/Tapp#1]
The app says there is an update (2.5), and redirects to GitHub /releases, which has no releases available. The website's download link gives a 404.

**Comment by HudsonGraeme** [comment]
Sorry about that! I've repaired the link on the website.

Here is a direct link: [https://apps.carspotter.ca/Tapp/releases/2.5/Tapp.app](https://apps.carspotter.ca/Tapp/releases/2.5/Tapp.app)
