### ISSUE TITLE
Crashes immediately when launched

### ISSUE THREAD

**Issue by psmith3** [HudsonGraeme/Tapp#3]
Running Mac OS X 10.13.4... Both 2.0.1 and 2.0 crash. Is this known?

**Comment by HudsonGraeme** [comment]
I had not known about the issue, thanks for telling me!

Does it display the gatekeeper message "Are you sure you want to open this application which was downloaded from GitHub.com?" when you launch the app, or nothing at all?
Additionally, the Tapp.dmg installer and Tapp.app application can be easily confused, make sure you're moving the .app to your Applications folder and launching Tapp from there.

Regards,

Spencer (HudsonGraeme)

**Comment by HudsonGraeme** [comment]
Okay.. I am able to reproduce the error on another computer, looking into possible causes.

**Comment by HudsonGraeme** [comment]
Fixed

**Comment by psmith3** [comment]
Where can I download the fixed version? The http://apps.carspotter.ca/tapp/ website does not work and all I see on GitHub is 2.0.1.
